name = "script-name-dev"
type = "webpack"
webpack_config = "./packages/worker/webpack.config.js"
account_id = "5a883b414d4090a1442b20361f3c43a9"
workers_dev = true

kv-namespaces = []

[site]
bucket = "./packages/client/build"
entry-point = "./packages/worker"

[env.production]
name = "script-name"